# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.1
        DEFAULT_BUMP: patch
        WITH_V: false

        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  package-and-publish-commons:
    runs-on: ubuntu-latest
    needs: generate-version

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
    - name: Pack
      run: |
        dotnet pack src/Devsulab.Common/ \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/DevsubLab.Common \
        -o packages

    - name: Publish
      run: dotnet nuget push packages/*.nupkg
