name: DevsuLab Common with Github App

on:
  push:
    branches: [ "main" ]
    
jobs:
  # Generate Access Token
  generate-token:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: workflow-application-token-action
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v2.1.0
      with:
        # GitHub Application Private Key value.
        application_private_key: ${{ secrets.GH_DEVSUAPP_PRIVATE_KEY }}
        # GitHub Application ID value.
        application_id: ${{ secrets.GH_DEVSUAPP_APP_ID }}
  # Generate The next Tag Version Number
  generate-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: github-tab-action
      uses: anothrNick/github-tag-action@1.67.0
      id: get_tag_bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 1.0.0
        DEFAULT_BUMP: patch
        WITH_V: false 
    outputs:
      new_version: ${{ steps.get_tag_bump.outputs.new_tag }}
  # Package and Publish Repo
  package-and-publish-repo:
    runs-on: ubuntu-latest
    needs: ["generate-version"]
    steps:
    - uses: actions/checkout@v3
    - name: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        config-file: nuget.config
      env:
        VERSION: ${{ needs.generate-version.outputs.new_version }}
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Pack
    - name: Pack
      run: |
          if [ -z "${{ needs.generate-version.outputs.new_version }}" ]; then
            echo "PackageVersion is not set. Aborting..."
            exit 1
          fi
          dotnet pack src/Devsulab.Common/ \
          --configuration Release \
          -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
          -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/DevsubLab.Common \
          -o packages
    # Publish
    - name: Publish
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}"
